import random
story = ['''I went to one of my aunt's place. I won't mention her real name so let's call her Riya. She was married to a navy personal and her husband was on a 6 month long mission when I went to her. To our luck COVID hit the world and a complete lockdown was declared.
She is a 33C-27–36 and one of the fairest person I know. No kids. She use to work out regularly like me and I was there for some documentation work. But due to lockdown we both were stuck in the same house.
Initially everything was normal. Infact we use to workout at home daily together. I use to sleep on sofa and she use to sleep on her bedroom. Everything was normal but 10 days passed by and I hadn't had sex. I was horny as fuck. One day I intentionally left my towel on sofa before going to shower. I asked her to pass my towel. She came as gave me my towel. I opened the door of the washroom and got my hand out but in such a way that she could see my dick and damn yes she saw that. I know most girls can't resist my 9+ inch dick. Next day I took this to a next level. While she was having shower, I acted like I'm sleeping on sofa, naked with just my towel on me. My dick was semi-hard and it was placed in a way that she could see that clearly. When she came out of washroom she was shocked but I acted like I'm sleeping. She gasped and stayed there seeing that for a minute.
After this she started acting exactly the way I wanted. She started wearing deep neck clothes. While workouts she started wearing normal bra instead of a sports bra. She started wearing saree more and more. One day I opened a tab of women wearing ultra low waist saree and left it open intentionally for her to see that. She saw that. She always use to wear saree even above her navel (high waist) but after seeing that tab she made some adjustments and wore her saree 6 inches below her navel. That was a big change on her body and was very clearly visible. I was stunned by seeing her that way. She even started wearing low waist clothes while workouts. One day I complaint her about heat on living room where I use to sleep on sofa. She immediately offered me to sleep with her on the bed under AC. I said yes and she had a sudective smile on her face.
At night when I entered the room I saw her wearing a small crop top and a ultra low waist hot pants. I immediately took of my shirt and went to bed. Before going to bed I had asked her to give me some medicine for leg's pain. Before sleeping she offered me a medicine that I understand was a Viagra. I acted like I took it but I didn't. At night she was shocked that I didn't had an erection so she touched my dick and put her hand inside my pant. I woke up immediately and kissed her. She kissed me back and then we both got naked. We started with 69 position and she came after 10–12 mins. My cock was rock hard. She opened her closest and got a condom. But that condom was not fitting my dick. It was small for me. I use to order a XL size for me. I started fucking her in multiple positions without condom. I fucked her 2 rounds for more than 140 mins. She came 7 times that night. My dick was inside her when I woke up next day. She was still sleeping. I immediately started fucking her again. She again came 3 times. After this she got some birth control pills and we use to live naked it the house and use to fuck everytime we can. In her 6 years of marriage she didn't had a baby. Most likely my uncle was impotent. So just before my uncle came back from duty she stopped having birth control pills and she got pregnant quickly. I started cumming inside her every time. Today I have a 2 year old daughter with my aunty and my uncle thinks that she is his daughter. Even today when I got to meet her, we don't talk. We just have sex. And it's fun!''',
'''I am an upper middle class family boy who studied engineering in reputated college. After finishing degree, I worked for one year and after that I planned to join coaching classes for government jobs.

I got in a coaching class and got a seperate house for me their. I always value my privacy. Chose that house since it was lonely with only few neighbours. Here comes the heroine. As I was there to study, I heard there were mess around us but none of them are good. Meanwhile I was searching my mom found a neighbour of age looked like late 20s. Mom told me she will be your maid clean the room and daily morning and evening and gives me food.

As mom liked her for some reason, I couldn't argue anymore. She was hot. But I couldn't accept. Since it feels like I was over reacting for having a maid for me while I came for exam preparation. I selected that institute since I can meet my girlfriend who was also near that institute.

She used to come and go. Weekly once atleast. We do have foreplay and all. My parents visit me monthly once. My maid was also helping me without disturbing. I always look at her body, waist, wet boobs, big ass. Damn sexy legs. It was just a single room building. If she comes she will be Infront of me only.

One day, me and my girlfriend got so intimate and removed her dress partially. While enjoying my gf, she entered the room and saw us like that. She looked at us and went away quickly. She didn't see my eyes and I didn't speak.

Nothing happened. So everything back to normal. One day I got cold fever, it was all raining. And even phone signals were not working. My maid decided to stay with me all night. Current got cut. She lighted a candle. Imagine it how it will be. A wet body damsel in saree standing Infront of you with a candle.

As I was covered with everything I got, my erection was not visible. She tried to apply balm on my chest while I was having my head in her lap. It was heavenly view for me. Big boobs. Shaking above me. As soon as put started applying balm she also kind of feeling warm. I felt it from the body heat. It was thunder I held her tightly. I released my hold quickly. She stood up. Checked the doors and windows. Simply came back to me and laid down next to me.
She was smiling at me for two minutes. I closed my eyes and tried to sleep. Few seconds later I felt an hand on my hand. Opened my eyes and saw her hand is taking my hand to her hip. I felt a shock. She pressed her hips with my hand. That's it. We have beautiful passionate sex.
Kissed her madly. Removed her saree. Got naked. Played with her body parts like baby. She enjoyed with me like hell. We didn't even speak until I finished it. She just signalled with eyes to ejaculate inside. That was my first penetrative sex. Morning she dressed up and gave a cute smile and dressed up Infront of me.
And due to heavy weather. One week was leave for us. One week was heavenly sexual with my maid. I asked her details. She was widow who married a military man. She was 32. I couldn't believe it. She just live there since it was her husband property now in her name.
After that she also helped me in studies by staying away whenever I study. She even blackmailed me to study properly and teached me tricks with girl making out. Even my girlfriend told my foreplay made her increases her lust. I gave that pleasure to maid that night. She never spoke too much. We were like friends with benefits for next one year.
I got cleared of my exams and got a job. I presuaded her to come to our home. My marriage proposal is going on with my girlfriend and also my sexual drive with my maid.
She told me to stop. But I couldn't control. I stopped it after marriage. But started it again since my girlfriend stops to have sex frequently. She is now in late 30s. But look like diva.''',
'''I have had it with all of them. I was 12 when I had sex with our housewife. When she did a pocha I could always see that she was not wearing panties and one day when I was alone and she had come to do her work she again started doing the pocha but this time I went behind her removed her skirt off and started licking her pussy she was loving and told me beta put your dick in my pussy and I did so she was really tight as hell man I loved it when I was about to cum she told me to cum on her body and I did. I loved the sight of her liking my cum off. Then whenever she was doing pocha and no one was watching I would put my dick into her pussy.

The next was turion teacher she was Indian too. She always wore really short skirts and sexy lingerie inside them I could always see it as her clothes were translucent. One day she didn't wear her panties and and was just going under the table to get my fallen pencil I say her beautiful pussy and say the she was masturbating. Then I went up and the time was almost over when I told her to get up I lifted up her skirt and put my fat dick into her asshole. She moaned loudly my mother came to check on us and found what we were doing then teacher held her had and I pulled out my dick and put it in my mom's pussy instead she said that this is wrong but I continued and then said that it's alright and then came right in my mom's uterus. Then I banged my teacher for 2 hours and then she left.''',
'''Once when i was in 8th, i was not able to correct my betl since its hook was broken, so my social science teacher when she saw this in the staff room called my and corrected my belt, in this proccess she unintentionally touched my penis and i liked it a lot.

There after everyday after the period when she would turn around after the class to fill the logbook, i used to go by her side and rub sometimes my hands and sometimes penis on her butt. After 2–3 days she reacted and called me to the staff room and cautioned me that it is not okay to do such things- i anyways told her that it was done by mistake but she insisted upon that it was not good. Atlast after 10–15 mins or so i agreed upon it cause she was friendly and told her that i liked to touch her, to which she said that she would touch my penis over my pants and this would end this topic- she did so such that i dont do it again and to any of my class girls. She did so but for just 3–4 seconds.

After 7–8 months when we went to school trip and everyone was getiing refreshed, i went to her room and she bent to unpack the luggage i quickly went to her back and rubbed my penis again in such a way that it felt unintentional but when she scolded me i told her that she too liked it and mean while went close to her face and again rubbed my penis from the front.

THEN AFTER 30 MINS OF REQUESTING SHE AGREED TO LET ME RUB MY PENIS ON HER BUTT BUT WITH A CONDITION THAT I WONT DO SO AGAIN AND IF I DID SHE WOULD COMPLAIN. SO I STARTED RUBBING MY PENIS UP -DOWN AND THE BEST PART IS I COULD FEEL HER GET WET',
'My mom is 37y , during my recent day's whenever my mom goes for bath ,she is forgetting (ig wantedly) her towel to take along with her,coz wherever she finishes her bathing,she call me and says to give her towel, Her way of asking the towel was soo different,she used to call me in her bedroom and tho she is naked , whenever I give her the towel she won't cover her naked body (she tries to seduces me) .So I just don't take these things seriously…

But the incident which happened on Holi will blow ur mind ……

As it was Holi,my mom don't want to play Holi(my dad was out of station),so she decided to not go outside on that day,but the neighbour aunties suddenly rushed in our home and splashed the colour on me and my mom,and then as it turned to a joyful moment she can't resist that,…all of those aunties took my mom and went to play Holi ,and my mom return home after 2hrs,.When she returned home her condition was very bad full of colours and she was so wet (she was wearing saree on Holi)and her whole saree was wet (imagine a wet looking horny mom was in my front), her boobs were visible through her wet blouse, and I was shocked…and then she asked me to help me to clean her, I gave her a cloth to clean her feet and then she directly went to the bathroom,…

She called me when she was in washroom and I saw her entirely naked,she was a sexy hot figure which I didn't know till now and I was shocked by seeing her naked,I pretended that I didn't see her,and she told me to put her saree and blouse in the washing machine …

Again she called me and I was very sacred,and she told me to rub her back with the soap ,and in between she said that u have to stay here till I'm done with my bathing… and I was completely shocked as she was naked and said to stay there and slowly my dick was erecting by seeing her ,and she was having her shower and I saw my mom boobs , vagina everything today,…as I was feeling full horny,and my mom suddenly told me to remove my clothes as I also didn't bath ,then I said “I don't want to bath here", then she said" no u helped me to bath and now I'll help u to bath" and the moment when she said this my dick was huge she saw my erected dick also as I'm wearing my shorts, then I was very slow to remove my clothes,she came closer to me and removed my short and pretend she didn't see my erected dick ,and then I was naked and she was also naked,that was the special feeling to me,then I turned on the shower I was running soap on my body ,she came near to me and took the soap and rubbed my whole body😶…she touched my penis too,and rubbed that area for 2minutes and I was so silent 😶… I didn't understood what was happening…and then my dick was erected,she was also feeling horny and placed my hand on her boobs (as I was seeing her boobs when she was rubbing my body),then she said “I know u want them ,u can do whatever u want now, FUCK ME!” and the moment she told this I gave a lusty eye contact to her and kissed her and we started kissing under the shower for 5min it was so pleasureable moment I ever had in my life,. And then we rinsed off and went to bedroom and sucked her vagina and her moans were soo cute ,I said I love her soo much ,and she she had sucked my dick for 2min as I was in hurry to fuck her ,and the first position I tried with my mom was cowgirl position,her moans were soo good (in between she told me to fuck me harder),and I was feeling like I was in heaven,we tried all the positions and at last she told me to not to cum in her pussy ,she wants to taste my cum once, when I was doing doggy style I got my cum I told her to show her face ,and all my cum was on her face ,I felt really happy and I kissed her and then we started cuddling and daily whenever we get chance we are doing all the positions of sex…''']

story_count=0